### ISSUE TITLE
Actions disabled 

### ISSUE THREAD

**Issue by findanna** [finddx/find.dxgap#285]
@andreranza @MikeJohnPage we have disabled actions, because we got an email that we were approaching the limit of 3,000 min too fast. 
I got a report and I saw that the actions you were running (especially yesterday) were taking a really long time to run.
Can you please check the workflow and why would it take so long?
![Screenshot 2023-12-01 at 09 18 35](https://github.com/finddx/find.dxgap/assets/62348391/16a07a40-8dc1-49fd-b7a8-9b0e48a4998a)

**Comment by findanna** [comment]
Closing now, I have enabled actions.

**Comment by andreranza** [comment]
Thanks!
